// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkEH99Q4iOumajAOt4xvKS5Wutn6xhOFU',
    appId: '1:939065976045:web:11dfef0cb87af10fa258e4',
    messagingSenderId: '939065976045',
    projectId: 'flutteryfirebase-250k8r',
    authDomain: 'flutteryfirebase-250k8r.firebaseapp.com',
    storageBucket: 'flutteryfirebase-250k8r.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWny5PIG-orq1ruqTVyvY0Xv5EIHFsGKk',
    appId: '1:939065976045:android:d2e9257794621c16a258e4',
    messagingSenderId: '939065976045',
    projectId: 'flutteryfirebase-250k8r',
    storageBucket: 'flutteryfirebase-250k8r.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4PmbBVxjsaGzMnJMbo8B486qAZv9bFPU',
    appId: '1:939065976045:ios:d0be0c4ebbfd2ff6a258e4',
    messagingSenderId: '939065976045',
    projectId: 'flutteryfirebase-250k8r',
    storageBucket: 'flutteryfirebase-250k8r.firebasestorage.app',
    androidClientId: '939065976045-g349hdgaputqnakvsloi7af3r93uu2t8.apps.googleusercontent.com',
    iosClientId: '939065976045-eddgf787671q2eakvihcpf2q5bihnuv6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4PmbBVxjsaGzMnJMbo8B486qAZv9bFPU',
    appId: '1:939065976045:ios:d0be0c4ebbfd2ff6a258e4',
    messagingSenderId: '939065976045',
    projectId: 'flutteryfirebase-250k8r',
    storageBucket: 'flutteryfirebase-250k8r.firebasestorage.app',
    androidClientId: '939065976045-g349hdgaputqnakvsloi7af3r93uu2t8.apps.googleusercontent.com',
    iosClientId: '939065976045-eddgf787671q2eakvihcpf2q5bihnuv6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkEH99Q4iOumajAOt4xvKS5Wutn6xhOFU',
    appId: '1:939065976045:web:9e4447be5bec28daa258e4',
    messagingSenderId: '939065976045',
    projectId: 'flutteryfirebase-250k8r',
    authDomain: 'flutteryfirebase-250k8r.firebaseapp.com',
    storageBucket: 'flutteryfirebase-250k8r.firebasestorage.app',
  );
}
